name: Gatsby CD 

on:
  release:
    branches: [prod]
    types: [published, created, edited]

jobs:
  push_to_deploy:
    name: GitHub Pages Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Push to correct repository with Git Sync
        uses: wei/git-sync@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source_repo: tomstrat/hive-website
          source_branch: prod
          destination_repo: electrichive/electrichive.github.io
          desination_branch: main 
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }}
          desination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}