name: Deploy to Staging

on:
    pull_request:
        branches: [dev]

jobs:
    build:
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - run: npm ci
            - run: npm run deploy:github

